{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subcults.fullname" . }}-frontend
  labels:
    {{- include "subcults.labels" . | nindent 4 }}
    {{- include "subcults.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "subcults.selectorLabels" (dict "root" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "subcults.labels" . | nindent 8 }}
        {{- include "subcults.selectorLabels" (dict "root" . "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ include "subcults.image" (dict "root" . "image" .Values.frontend.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
