{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subcults.fullname" . }}-api
  labels:
    {{- include "subcults.labels" . | nindent 4 }}
    {{- include "subcults.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "subcults.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
---
{{- end }}
{{- if .Values.indexer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subcults.fullname" . }}-indexer
  labels:
    {{- include "subcults.labels" . | nindent 4 }}
    {{- include "subcults.selectorLabels" (dict "root" . "component" "indexer") | nindent 4 }}
spec:
  type: {{ .Values.indexer.service.type }}
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.indexer.service.port }}
      targetPort: {{ .Values.indexer.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "subcults.selectorLabels" (dict "root" . "component" "indexer") | nindent 4 }}
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subcults.fullname" . }}-frontend
  labels:
    {{- include "subcults.labels" . | nindent 4 }}
    {{- include "subcults.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "subcults.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
{{- end }}
