import { useLocation } from 'react-router-dom';
import { PageMeta } from '../components/PageMeta';

const privacySections = [
  ['Information we collect', 'Account information includes your email address, handle, display name, role, and account security records. If you link an AT Protocol account, we store its public DID, handle, granted scopes, link status, and encrypted session material. Activity may include RSVPs, creator-access requests, consent choices, published content, and support messages. Basic network, browser, request, security, and error data is processed to operate and protect the service.'],
  ['Location and protected venues', 'You can browse by city without sharing device location. If you choose device location later, Subcult is designed to use an approximate location for discovery. Public records may contain a disclosed city, region, venue, or server-approved map point. Exact protected coordinates and addresses remain in private storage and are released only to an authorized account, such as an eligible RSVP or ticket holder. We do not infer an artist’s current location from an itinerary, device, purchase, or RSVP.'],
  ['How we use information', 'We use information to create and secure accounts; provide discovery, RSVP, publishing, consent, and support features; prevent abuse; maintain source and correction history; diagnose failures; comply with law; and improve service reliability. We do not turn an RSVP, purchase, follow, or scene relationship into email, push, or marketing permission.'],
  ['Public and portable records', 'Creators choose which disclosure-safe records to publish. Public profiles, scenes, events, tours, appearances, and provenance assertions may be written to the creator’s AT Protocol repository and copied into public discovery indexes. Public decentralized records can be retained by third parties even after Subcult removes its own projection. Private drafts, contacts, consent history, delivery history, payments, authorization grants, and protected coordinates are not published to AT Protocol.'],
  ['When we share information', 'We share the minimum information needed with infrastructure, email, mapping, payment, fraud-prevention, and messaging providers that help operate Subcult. Public content is shared through public APIs and AT Protocol. We may disclose information to comply with law, protect people and the service, or complete a business transfer subject to appropriate safeguards. We do not sell private contact information or messaging consent.'],
  ['Retention and security', 'We keep account and service records while they are needed to provide Subcult, preserve public-record provenance, resolve disputes, prevent abuse, and meet legal obligations. Retention varies by record and legal requirement. Sensitive contact values, OAuth sessions, and protected location data are encrypted or hashed as appropriate. No service can promise absolute security.'],
  ['Your choices and rights', 'You can decline device location, revoke channel-specific messaging permission, unlink an AT Protocol account, and ask to access, correct, export, or delete eligible personal information. Public AT Protocol copies may remain outside Subcult’s control. Depending on where you live, you may also have rights to object, restrict processing, appeal a decision, or complain to a regulator.'],
  ['Cookies and local storage', 'Subcult uses essential browser storage and cookies for authentication, security, preferences, and application operation. The public beta does not use cross-site behavioral advertising. Browser signals do not disable processing required to provide and secure the service.'],
  ['Children and international use', 'Subcult is not directed to children under 13, and we do not knowingly collect their personal information. Information may be processed in the United States and other locations where service providers operate, subject to applicable safeguards.'],
  ['Contact us', 'For privacy questions or requests, email info@subcult.tv. We may need to verify your identity before completing a request.'],
] as const;

const termsSections = [
  ['Using Subcult', 'You must be legally able to accept these Terms and provide accurate account information. You are responsible for activity under your account and for keeping email and linked AT Protocol accounts secure. The service is a beta and may change, pause, or contain errors.'],
  ['Accounts and linked services', 'Passwordless email is the recovery path for a Subcult account. Linking an AT Protocol account is optional until you publish portable public content. Your PDS or another third-party service may apply separate terms. Unlinking stops future authorized writes but does not erase public records already distributed outside Subcult.'],
  ['Creator publishing', 'Only publish material you have the right and authority to publish. Keep dates, billing, venue disclosure, and source claims accurate. Public Studio publishing writes disclosure-safe records to the linked creator repository; private drafts and protected details stay in Subcult’s private systems. Corrections, cancellations, and source history may remain visible for accountability.'],
  ['Your content', 'You retain ownership of content you submit. You grant Subcult a worldwide, non-exclusive license to host, reproduce, format, index, display, and distribute that content only as needed to operate, secure, and promote the service and its public records. This license ends when the content is removed from Subcult, except for backups, legal retention, provenance history, and copies distributed through decentralized networks.'],
  ['Acceptable use', 'Do not impersonate others; publish deceptive claims; scrape or expose protected data; evade access controls; harass people; send unlawful or unauthorized messages; upload malware; disrupt the service; or use Subcult to violate privacy, intellectual-property, consumer-protection, ticketing, or other laws.'],
  ['RSVPs, consent, and messaging', 'An RSVP records event intent only. It is not consent to email, push, SMS, or marketing. Creators must use only the channels, purposes, senders, and audiences covered by an active permission and must honor revocation and suppression immediately.'],
  ['Payments and third parties', 'Purchases and connected services may be processed by third parties under their own terms and privacy policies. Subcult does not control third-party availability, content, repository retention, ticket fulfillment, or refund rules. Any price and refund terms shown at checkout control that transaction.'],
  ['Enforcement and termination', 'We may restrict or end access, quarantine public records, or remove Subcult projections when reasonably needed for security, legal compliance, abuse prevention, or violation of these Terms. You may stop using Subcult at any time. Provisions that by their nature should survive will survive termination.'],
  ['Disclaimers and liability', 'Subcult is provided “as is” and “as available” to the extent permitted by law. We do not guarantee event accuracy, attendance, availability, delivery, or uninterrupted indexing. To the extent permitted by law, Subcult is not liable for indirect, incidental, special, consequential, or punitive damages. Nothing in these Terms limits rights or liability that cannot legally be limited.'],
  ['Changes and contact', 'We may update these Terms as the service changes. Material changes will be identified by a new effective date and, when appropriate, an in-product or email notice. Questions can be sent to info@subcult.tv.'],
] as const;

export function LegalPage() {
  const privacy = useLocation().pathname === '/privacy'; const sections = privacy ? privacySections : termsSections;
  return <main className="content-wrap max-w-4xl py-16"><PageMeta title={privacy ? 'Privacy Policy' : 'Terms of Service'}/><p className="eyebrow">Subcult public beta</p><h1 className="font-display mt-4 text-6xl uppercase">{privacy ? 'Privacy Policy' : 'Terms of Service'}</h1><p className="mt-4 font-mono text-xs uppercase tracking-wider text-foreground-muted">Effective August 9, 2026</p><p className="mt-8 max-w-3xl text-lg leading-8 text-foreground-secondary">{privacy ? 'This policy explains what Subcult collects, why it is used, what becomes public, and the choices available to you.' : 'These terms govern your use of Subcult, including discovery, accounts, creator publishing, and portable public records.'}</p><div className="mt-10 grid gap-10">{sections.map(([title, body]) => <section className="dossier-rule pt-7" key={title}><h2 className="font-display text-3xl uppercase text-foreground">{title}</h2><p className="mt-4 leading-8 text-foreground-secondary">{body}</p></section>)}</div></main>;
}
